# Generated by Django 5.1.7 on 2025-04-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DentalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaints', models.TextField(blank=True, null=True)),
                ('history_of_present_illness', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('past_dental_history', models.TextField(blank=True, null=True)),
                ('personal_history', models.TextField(blank=True, null=True)),
                ('general_examination', models.TextField(blank=True, null=True)),
                ('general_examination_intraoral', models.TextField(blank=True, null=True)),
                ('local_examination_extraoral', models.TextField(blank=True, null=True)),
                ('soft_tissue', models.TextField(blank=True, null=True)),
                ('dentition', models.JSONField(blank=True, null=True)),
                ('periodontal_status', models.TextField(blank=True, null=True)),
                ('investigation', models.ImageField(blank=True, null=True, upload_to='investigations/')),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('doctor_signature', models.ImageField(default='signatures/default_doctor_signature.png', upload_to='signatures/')),
                ('patient_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_days', models.IntegerField(default=1)),
                ('medicine_times', models.JSONField()),
                ('meal_times', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
