# Generated by Django 5.1.7 on 2025-03-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DOCTOR', '0001_initial'),
        ('RECEPTION', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalexamination',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dental_examinations', to='RECEPTION.patientbooking'),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_examinations', to='RECEPTION.patient'),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='RECEPTION.patientbooking'),
        ),
    ]
