# Generated by Django 5.1.7 on 2025-04-01 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DOCTOR', '0002_initial'),
        ('RECEPTION', '0001_initial'),
        ('SUPER_ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineprescription',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='SUPER_ADMIN.pharmaceuticalmedicine'),
        ),
        migrations.AddField(
            model_name='treatmentbill',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_bills', to='RECEPTION.patientbooking'),
        ),
        migrations.AddField(
            model_name='treatmentbill',
            name='dental_examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttreatment_bills', to='DOCTOR.dentalexamination'),
        ),
        migrations.AddField(
            model_name='treatmentbill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RECEPTION.patient'),
        ),
    ]
