# Generated by Django 5.1.7 on 2025-04-01 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0003_initial'),
        ('RECEPTION', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentalexamination',
            name='dentition',
        ),
        migrations.RemoveField(
            model_name='dentalexamination',
            name='doctor_signature',
        ),
        migrations.RemoveField(
            model_name='dentalexamination',
            name='investigation',
        ),
        migrations.RemoveField(
            model_name='dentalexamination',
            name='past_dental_history',
        ),
        migrations.RemoveField(
            model_name='dentalexamination',
            name='patient_signature',
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dentalexamination',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dental_examinations', to='RECEPTION.patientbooking'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='investigations/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dental_examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='DOCTOR.dentalexamination')),
            ],
        ),
    ]
