# Generated by Django 5.1.7 on 2025-04-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0004_remove_dentalexamination_dentition_and_more'),
        ('RECEPTION', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentitionTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color_code', models.CharField(help_text='Hex color code for treatment (e.g., #FF0000 for red)', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Dentition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_teeth', models.JSONField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentitions', to='RECEPTION.patientbooking')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentitions', to='RECEPTION.patient')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dentition_treatments', to='DOCTOR.dentitiontreatment')),
            ],
        ),
    ]
