# Generated by Django 5.1.7 on 2025-04-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0005_dentitiontreatment_dentition'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentbill',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentbill',
            name='dental_examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_bills', to='DOCTOR.dentalexamination'),
        ),
    ]
