# Generated by Django 5.1.7 on 2025-03-07 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUPERADMIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('General Dentist', 'General Dentist'), ('Orthodontist', 'Orthodontist'), ('Periodontist', 'Periodontist'), ('Endodontist', 'Endodontist'), ('Prosthodontist', 'Prosthodontist')], max_length=100)),
                ('experience_years', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('educational_certificate', models.FileField(blank=True, null=True, upload_to='DOCTOR/certificates/')),
                ('medical_license', models.FileField(blank=True, null=True, upload_to='DOCTOR/licenses/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='SUPERADMIN.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
