# Generated by Django 5.1.7 on 2025-03-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RECEPTION', '0001_initial'),
        ('SUPERADMIN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SUPERADMIN.branch'),
        ),
        migrations.AddField(
            model_name='patientbooking',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_appointments', to='SUPERADMIN.branch'),
        ),
        migrations.AddField(
            model_name='patientbooking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='SUPERADMIN.doctor'),
        ),
        migrations.AddField(
            model_name='patientbooking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='RECEPTION.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='patientbooking',
            unique_together={('doctor', 'appointment_date', 'appointment_time')},
        ),
    ]
