# Generated by Django 5.1.7 on 2025-03-29 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RECEPTION', '0001_initial'),
        ('SUPER_ADMIN', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SUPER_ADMIN.branch'),
        ),
        migrations.AddField(
            model_name='patientbooking',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_appointments', to='SUPER_ADMIN.branch'),
        ),
        migrations.AddField(
            model_name='patientbooking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='SUPER_ADMIN.doctor'),
        ),
        migrations.AddField(
            model_name='patientbooking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='RECEPTION.patient'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RECEPTION.patientbooking'),
        ),
    ]
