# Generated by Django 5.1.7 on 2025-03-08 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RECEPTION', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 1 (Upper Right Third Molar)')),
                ('tooth_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 2 (Upper Right Second Molar)')),
                ('tooth_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 3 (Upper Right First Molar)')),
                ('tooth_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 4 (Upper Right Second Premolar)')),
                ('tooth_5', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 5 (Upper Right First Premolar)')),
                ('tooth_6', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 6 (Upper Right Canine)')),
                ('tooth_7', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 7 (Upper Right Lateral Incisor)')),
                ('tooth_8', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 8 (Upper Right Central Incisor)')),
                ('tooth_9', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 9 (Upper Left Central Incisor)')),
                ('tooth_10', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 10 (Upper Left Lateral Incisor)')),
                ('tooth_11', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 11 (Upper Left Canine)')),
                ('tooth_12', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 12 (Upper Left First Premolar)')),
                ('tooth_13', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 13 (Upper Left Second Premolar)')),
                ('tooth_14', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 14 (Upper Left First Molar)')),
                ('tooth_15', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 15 (Upper Left Second Molar)')),
                ('tooth_16', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 16 (Upper Left Third Molar)')),
                ('tooth_17', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 17 (Lower Left Third Molar)')),
                ('tooth_18', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 18 (Lower Left Second Molar)')),
                ('tooth_19', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 19 (Lower Left First Molar)')),
                ('tooth_20', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 20 (Lower Left Second Premolar)')),
                ('tooth_21', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 21 (Lower Left First Premolar)')),
                ('tooth_22', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 22 (Lower Left Canine)')),
                ('tooth_23', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 23 (Lower Left Lateral Incisor)')),
                ('tooth_24', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 24 (Lower Left Central Incisor)')),
                ('tooth_25', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 25 (Lower Right Central Incisor)')),
                ('tooth_26', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 26 (Lower Right Lateral Incisor)')),
                ('tooth_27', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 27 (Lower Right Canine)')),
                ('tooth_28', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 28 (Lower Right First Premolar)')),
                ('tooth_29', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 29 (Lower Right Second Premolar)')),
                ('tooth_30', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 30 (Lower Right First Molar)')),
                ('tooth_31', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 31 (Lower Right Second Molar)')),
                ('tooth_32', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tooth 32 (Lower Right Third Molar)')),
                ('blood_pressure', models.CharField(blank=True, max_length=50, null=True, verbose_name='Blood Pressure')),
                ('temperature', models.CharField(blank=True, max_length=50, null=True, verbose_name='Temperature')),
                ('pulse_rate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pulse Rate')),
                ('respiratory_rate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Respiratory Rate')),
                ('weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Weight')),
                ('height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Height')),
                ('bmi', models.CharField(blank=True, max_length=50, null=True, verbose_name='BMI')),
                ('general_observations', models.TextField(blank=True, null=True, verbose_name='General Observations')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnosis')),
                ('treatment_plan', models.TextField(blank=True, null=True, verbose_name='Treatment Plan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='RECEPTION.patient')),
            ],
            options={
                'verbose_name': 'Patient Examination',
                'verbose_name_plural': 'Patient Examinations',
            },
        ),
    ]
