# Generated by Django 5.1.7 on 2025-03-10 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0001_initial'),
        ('RECEPTION', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quadrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, 'Upper Right'), (2, 'Upper Left'), (3, 'Lower Left'), (4, 'Lower Right')], unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DentalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='RECEPTION.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('carious', 'Carious'), ('filled', 'Filled'), ('missing', 'Missing'), ('needs-cleaning', 'Needs Cleaning')], default='healthy', max_length=20)),
                ('quadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='DOCTOR.quadrant')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('filling', 'Filling'), ('root-canal', 'Root Canal'), ('extraction', 'Extraction'), ('crown', 'Crown'), ('cleaning', 'Professional Cleaning'), ('implant', 'Implant')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='DOCTOR.tooth')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientExamination',
        ),
    ]
