# Generated by Django 5.1.7 on 2025-03-10 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0002_quadrant_dentalchart_tooth_treatment_and_more'),
        ('RECEPTION', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_visit', models.DateField(blank=True, null=True)),
                ('previous_sugar_level', models.CharField(blank=True, max_length=10, null=True)),
                ('previous_pressure_level', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_notes', models.TextField(blank=True, null=True)),
                ('sugar_level', models.CharField(max_length=10)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_examinations', to='RECEPTION.patientbooking')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_examinations', to='RECEPTION.patient')),
            ],
        ),
    ]
