# Generated by Django 5.1.7 on 2025-03-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0003_generalexamination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalexamination',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='sugar_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
