# Generated by Django 5.1.7 on 2025-03-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalexamination',
            name='selected_teeth',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dentalexamination',
            name='treatments',
            field=models.JSONField(default=list),
        ),
    ]
