# Generated by Django 5.1.7 on 2025-03-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0004_alter_generalexamination_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('filling', 'Filling'), ('root-canal', 'Root Canal'), ('extraction', 'Extraction'), ('crown', 'Crown'), ('teeth-cleaning', 'Teeth Cleaning'), ('implant', 'Implant'), ('teeth-whitening', 'Teeth Whitening'), ('veneers', 'Veneers'), ('braces', 'Braces'), ('bonding', 'Bonding'), ('dentures', 'Dentures')], max_length=20),
        ),
    ]
