# Generated by Django 5.1.7 on 2025-03-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0005_alter_treatment_treatment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quadrant',
            name='name',
        ),
    ]
