# Generated by Django 5.1.7 on 2025-03-25 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0005_rename_price_treatmentbill_balance_amount_and_more'),
        ('RECEPTION', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineprescription',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='medicineprescription',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='treatmentbill',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='treatmentbill',
            name='dental_examination',
        ),
        migrations.RemoveField(
            model_name='treatmentnote',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='dentalexamination',
            name='selected_teeth',
        ),
        migrations.RemoveField(
            model_name='dentalexamination',
            name='treatments',
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='chief_complaints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='dentition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='doctor_signature',
            field=models.ImageField(default='signatures/default_doctor_signature.png', upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='general_examination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='general_examination_intraoral',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='history_of_present_illness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='investigation',
            field=models.ImageField(blank=True, null=True, upload_to='investigations/'),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='local_examination_extraoral',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='past_dental_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='patient_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='periodontal_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='personal_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='soft_tissue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalexamination',
            name='treatment_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentalexamination',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dental_examinations', to='RECEPTION.patientbooking'),
        ),
        migrations.DeleteModel(
            name='GeneralExamination',
        ),
        migrations.DeleteModel(
            name='MedicinePrescription',
        ),
        migrations.DeleteModel(
            name='TreatmentBill',
        ),
        migrations.DeleteModel(
            name='TreatmentNote',
        ),
    ]
