# Generated by Django 5.1.7 on 2025-03-11 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0006_remove_quadrant_name'),
        ('RECEPTION', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalchart',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dental_examinations', to='RECEPTION.patientbooking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dentalchart',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_examinations', to='RECEPTION.patient'),
        ),
    ]
