# Generated by Django 5.1.7 on 2025-03-26 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0006_remove_medicineprescription_booking_and_more'),
        ('RECEPTION', '0002_initial'),
        ('SUPERADMIN', '0002_alter_doctor_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_days', models.IntegerField(default=1)),
                ('medicine_times', models.JSONField()),
                ('meal_times', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='RECEPTION.patientbooking')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='SUPERADMIN.pharmaceuticalmedicine')),
            ],
        ),
    ]
