# Generated by Django 5.1.7 on 2025-03-26 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0007_medicineprescription'),
        ('RECEPTION', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_bills', to='RECEPTION.patientbooking')),
                ('dental_examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttreatment_bills', to='DOCTOR.dentalexamination')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RECEPTION.patient')),
            ],
        ),
    ]
