# Generated by Django 5.1.7 on 2025-03-12 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0007_dentalchart_booking_alter_dentalchart_patient'),
        ('RECEPTION', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooth',
            name='quadrant',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='tooth',
        ),
        migrations.CreateModel(
            name='DentalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_teeth', models.JSONField()),
                ('treatments', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_records', to='RECEPTION.patientbooking')),
            ],
        ),
        migrations.DeleteModel(
            name='DentalChart',
        ),
        migrations.DeleteModel(
            name='Quadrant',
        ),
        migrations.DeleteModel(
            name='Tooth',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
