# Generated by Django 5.1.7 on 2025-03-12 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0008_remove_tooth_quadrant_remove_treatment_tooth_and_more'),
        ('RECEPTION', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalexamination',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dental_examinations', to='RECEPTION.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dentalexamination',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_examinations', to='RECEPTION.patientbooking'),
        ),
    ]
