# Generated by Django 5.1.7 on 2025-03-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0008_treatmentbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentbill',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
