# Generated by Django 5.1.7 on 2025-03-12 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0009_dentalexamination_patient_and_more'),
        ('RECEPTION', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_notes', to='RECEPTION.patientbooking')),
            ],
        ),
    ]
