# Generated by Django 5.1.7 on 2025-03-13 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0010_treatmentnote'),
        ('RECEPTION', '0001_initial'),
        ('SUPERADMIN', '0003_supplier_pharmaceuticalmedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_days', models.IntegerField(default=1)),
                ('medicine_times', models.JSONField()),
                ('meal_times', models.JSONField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='RECEPTION.patientbooking')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='SUPERADMIN.pharmaceuticalmedicine')),
            ],
        ),
    ]
