# Generated by Django 5.1.7 on 2025-03-13 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTOR', '0011_medicineprescription'),
        ('RECEPTION', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_billing', to='RECEPTION.patientbooking')),
                ('dental_examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_billing', to='DOCTOR.dentalexamination')),
            ],
        ),
    ]
